<?php

// Copy this file to config.php on the server and adjust values if needed.

return [
    'company_name' => 'Karadag Celik',
    'from_email' => 'info@karadagcelik.com',
    'from_name' => 'Karadag Celik',
    'reply_to' => 'info@karadagcelik.com',
    'notification_emails' => [
        'info@karadagcelik.com',
    ],
    // Use a long random value. It protects the one-time admin installation page.
    'setup_key' => 'replace-with-a-long-random-key',
    // Database values can also be generated by admin/install.php into database.local.php.
    'database' => [
        'host' => '',
        'port' => 3306,
        'name' => '',
        'user' => '',
        'password' => '',
        'charset' => 'utf8mb4',
    ],
    'google' => [
        'client_id' => '',
        'client_secret' => '',
        'redirect_uri' => 'https://karadagcelik.com/account/google-callback.php',
    ],
    // Store uploads outside public_html when possible.
    // If this path is not writable, api/common.php falls back to a local private_uploads folder.
    'upload_dir' => dirname(__DIR__, 3) . DIRECTORY_SEPARATOR . 'karadag_private_uploads',
    'max_file_bytes' => 25 * 1024 * 1024,
    'allowed_extensions' => [
        'dxf', 'dwg', 'pdf', 'step', 'stp', 'iges', 'igs', 'zip', 'rar', 'jpg', 'jpeg', 'png',
    ],
];
